# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- garth-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-paginate
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag

# 3. Gem settings
paginate: 10 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts

# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "KKTRKKT의 기술블로그" # Site name or title
logo: "/assets/logo.svg" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "들어와주셔서 감사합니다 _ _" # Site description and default description
url: "https://kktrkkt.github.io" # Site url
baseurl: ""
